- type: statusIcon
  parent: CMJobIconBase
  id: JobIconCorrespondent
  icon:
    sprite: _CM14/Interface/cm_job_icons.rsi
    state: hudsquad #todo cm14 correspondent icon

- type: statusIcon
  parent: CMJobIconBase
  id: JobIconSurvivor
  icon:
    sprite: _CM14/Interface/cm_job_icons.rsi
    state: hudsquad #todo cm14 survivor icon
